apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  selector:
    app: webapp
    # give this when there is pods and service for selector and labels --
    #release: 0


  ports:
  - name: http
    port: 80
    nodePort: 30080
# if you are running on any cloud provider remove the nodePort and change type as LoadBalancer
  type: NodePort
