apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-docker
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: spring-boot-docker
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: spring-boot-docker
    spec:
      containers:
      - name: spring-boot-docker
        image: gcr.io/spring-kube/spring-docker
